import mongoose, {Schema, SchemaTypes} from "mongoose";
import type {Chu3UserPlaylogType} from "../types/userplaylog.types.ts";

const chu3UserPlaylogSchema = new Schema<Chu3UserPlaylogType>({
	_id: {type: SchemaTypes.ObjectId, auto: true},

	cardId: {type: String, ref: "Card", required: true},

	romVersion: {type: String},
	orderId: {type: Number},
	sortNumber: {type: Number},
	placeId: {type: Number},
	playDate: {type: Date},
	userPlayDate: {type: Date},
	musicId: {type: Number},
	level: {type: Number},
	customId: {type: Number},
	playedUserId1: {type: Number},
	playedUserId2: {type: Number},
	playedUserId3: {type: Number},
	playedUserName1: {type: String},
	playedUserName2: {type: String},
	playedUserName3: {type: String},
	playedMusicLevel1: {type: Number},
	playedMusicLevel2: {type: Number},
	playedMusicLevel3: {type: Number},
	playedCustom1: {type: Number},
	playedCustom2: {type: Number},
	playedCustom3: {type: Number},
	track: {type: Number},
	score: {type: Number},
	rank: {type: Number},
	maxCombo: {type: Number},
	maxChain: {type: Number},
	rateTap: {type: Number},
	rateHold: {type: Number},
	rateSlide: {type: Number},
	rateAir: {type: Number},
	rateFlick: {type: Number},
	judgeGuilty: {type: Number},
	judgeAttack: {type: Number},
	judgeJustice: {type: Number},
	judgeCritical: {type: Number},
	judgeHeaven: {type: Number},
	eventId: {type: Number},
	playerRating: {type: Number},
	isNewRecord: {type: Boolean},
	isFullCombo: {type: Boolean},
	fullChainKind: {type: Number},
	isAllJustice: {type: Boolean},
	isContinue: {type: Boolean},
	isFreeToPlay: {type: Boolean},
	characterId: {type: Number},
	charaIllustId: {type: Number},
	skillId: {type: Number},
	playKind: {type: Number},
	isClear: {type: Boolean},
	skillLevel: {type: Number},
	skillEffect: {type: Number},
	placeName: {type: String},
	commonId: {type: Number},
	regionId: {type: Number},
	machineType: {type: Number},
	ticketId: {type: Number},
	monthPoint: {type: Number},
	eventPoint: {type: Number, default: 0},
});

chu3UserPlaylogSchema.index({cardId: 1}, {unique:false});

export const Chu3UserPlaylog = mongoose.model("Chu3UserPlaylog", chu3UserPlaylogSchema);