import mongoose, {Schema, SchemaTypes} from "mongoose";
import type {Chu3UserGameOptionType} from "../types/usergameoption.types.ts";

const chu3UserGameOptionSchema = new Schema<Chu3UserGameOptionType>({
	_id: {type: SchemaTypes.ObjectId, auto: true},

	cardId: {type: String, ref: "Card", required: true, unique: true},

	bgInfo: {type: Number},
	fieldColor: {type: Number},
	guideSound: {type: Number},
	soundEffect: {type: Number},
	guideLine: {type: Number},
	speed: {type: Number},
	optionSet: {type: Number},
	matching: {type: Number},
	judgePos: {type: Number},
	rating: {type: Number},
	judgeCritical: {type: Number},
	judgeJustice: {type: Number},
	judgeAttack: {type: Number},
	headphone: {type: Number},
	playerLevel: {type: Number},
	successTap: {type: Number},
	successExTap: {type: Number},
	successSlideHold: {type: Number},
	successAir: {type: Number},
	successFlick: {type: Number},
	successSkill: {type: Number},
	successTapTimbre: {type: Number},
	privacy: {type: Number},
	mirrorFumen: {type: Number},
	selectMusicFilterLv: {type: Number},
	sortMusicFilterLv: {type: Number},
	sortMusicGenre: {type: Number},
	categoryDetail: {type: Number},
	judgeTimingOffset: {type: Number},
	playTimingOffset: {type: Number},
	fieldWallPosition: {type: Number},
	resultVoiceShort: {type: Number},
	notesThickness: {type: Number},
	judgeAppendSe: {type: Number},
	trackSkip: {type: Number},
	hardJudge: {type: Number},
	speed_120: {type: Number},
	fieldWallPosition_120: {type: Number},
	playTimingOffset_120: {type: Number},
	judgeTimingOffset_120: {type: Number},
	ext1: {type: Number},
	ext2: {type: Number},
	ext3: {type: Number},
	ext4: {type: Number},
	ext5: {type: Number},
	ext6: {type: Number},
	ext7: {type: Number},
	ext8: {type: Number},
	ext9: {type: Number},
	ext10: {type: Number},
});

export const Chu3UserGameOption = mongoose.model("Chu3UserGameOption", chu3UserGameOptionSchema);