import dotenv from "dotenv";

dotenv.config();

const {
	MONGO_URI,
	ALLNET_HOST,
	AIME_SECRET,
	SESSION_SECRET,
	AIME_KEY,
	DEFAULT_CHU3_MATCHING_URI,
	DEFAULT_CHU3_MATCHING_REFLECTOR,
	SCORES_SERVER,
	WEBUI_URL,
	ADMIN_ID,
	DISCORD_CLIENT_ID,
	DISCORD_CLIENT_SECRET,
	KEYCHIP_AUTH
} = process.env;

if (!MONGO_URI||!ALLNET_HOST||!AIME_SECRET||!AIME_KEY||!SCORES_SERVER||!SESSION_SECRET) {
	throw new Error("Missing environment variables");
}

export const config = {
	MONGO_URI,
	ALLNET_HOST,
	SESSION_SECRET,
	AIME_SECRET,
	AIME_KEY,
	DEFAULT_CHU3_MATCHING_URI: DEFAULT_CHU3_MATCHING_URI || "",
	DEFAULT_CHU3_MATCHING_REFLECTOR: DEFAULT_CHU3_MATCHING_REFLECTOR || "",
	SCORES_SERVER: SCORES_SERVER,
	WEBUI_URL: WEBUI_URL || "http://localhost",
	DISCORD_CLIENT_ID: DISCORD_CLIENT_ID|| "",
	DISCORD_CLIENT_SECRET: DISCORD_CLIENT_SECRET || "",
	ADMIN_ID: ADMIN_ID || "",
	KEYCHIP_AUTH: KEYCHIP_AUTH==="true"
};