import dotenv from "dotenv";

dotenv.config();

const {
	MONGO_URI,
	ALLNET_HOST,
	AIME_SECRET,
	AIME_KEY,
	DEFAULT_CHU3_MATCHING_URI,
	DEFAULT_CHU3_MATCHING_REFLECTOR,
	SCORES_SERVER
} = process.env;

if (!MONGO_URI||!ALLNET_HOST||!AIME_SECRET||!AIME_KEY||!SCORES_SERVER) {
	throw new Error("Missing environment variables");
}

export const config = {
	MONGO_URI,
	ALLNET_HOST,
	AIME_SECRET,
	AIME_KEY,
	DEFAULT_CHU3_MATCHING_URI: DEFAULT_CHU3_MATCHING_URI || "",
	DEFAULT_CHU3_MATCHING_REFLECTOR: DEFAULT_CHU3_MATCHING_REFLECTOR || "",
	SCORES_SERVER: SCORES_SERVER
};