import mongoose, {Schema, SchemaTypes} from "mongoose";
import type {Mai2UserOptionType} from "../types/useroption.types.ts";

const mai2UserOptionSchema = new Schema<Mai2UserOptionType>({
	_id: {type: SchemaTypes.ObjectId, auto: true},

	userId: {type: String, ref: "Card", required: true, unique: true},

	optionKind: {type: Number, default: 0},
	noteSpeed: {type: Number, default: 5},
	slideSpeed: {type: Number, default: 5},
	touchSpeed: {type: Number, default: 5},
	tapDesign: {type: Number, default: 0},
	holdDesign: {type: Number, default: 0},
	slideDesign: {type: Number, default: 0},
	starType: {type: Number, default: 0},
	outlineDesign: {type: Number, default: 0},
	noteSize: {type: Number, default: 0},
	slideSize: {type: Number, default: 0},
	touchSize: {type: Number, default: 0},
	starRotate: {type: Number, default: 0},
	dispCenter: {type: Number, default: 0},
	dispChain: {type: Number, default: 1},
	dispRate: {type: Number, default: 0},
	dispBar: {type: Number, default: 1},
	touchEffect: {type: Number, default: 1},
	submonitorAnimation: {type: Number, default: 1},
	submonitorAchieve: {type: Number, default: 1},
	submonitorAppeal: {type: Number, default: 1},
	matching: {type: Number, default: 0},
	trackSkip: {type: Number, default: 0},
	brightness: {type: Number, default: 5},
	mirrorMode: {type: Number, default: 0},
	dispJudge: {type: Number, default: 1},
	dispJudgePos: {type: Number, default: 0},
	dispJudgeTouchPos: {type: Number, default: 0},
	adjustTiming: {type: Number, default: 0},
	judgeTiming: {type: Number, default: 0},
	ansVolume: {type: Number, default: 5},
	tapHoldVolume: {type: Number, default: 5},
	criticalSe: {type: Number, default: 1},
	tapSe: {type: Number, default: 5},
	breakSe: {type: Number, default: 5},
	breakVolume: {type: Number, default: 5},
	exSe: {type: Number, default: 5},
	exVolume: {type: Number, default: 5},
	slideSe: {type: Number, default: 5},
	slideVolume: {type: Number, default: 5},
	touchHoldVolume: {type: Number, default: 5},
	damageSeVolume: {type: Number, default: 5},
	headPhoneVolume: {type: Number, default: 5},
	sortTab: {type: Number, default: 0},
	sortMusic: {type: Number, default: 0},
	outFrameType: {type: Number, default: 0},
	breakSlideVolume: {type: Number, default: 5},
	touchVolume: {type: Number, default: 5},
});

export const Mai2UserOptionModel = mongoose.model<Mai2UserOptionType>("Mai2UserOption", mai2UserOptionSchema);